apiVersion: batch/v1
kind: Job
metadata:
  name: download-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: download-job
        env:
          - name: KAFKA_BROKER
            value: "10.42.0.12:9092"
          - name: KAFKA_BROKER
            valueFrom:
              secretKeyRef:
                name: alpha-advantage-apikey
                key: value
        image: black:latest
        command: ["black",  "printEnv" ]
  backoffLimit: 4
