package main

var sp500 = []string{
	"AAPL", "MSFT", "AMZN", "FB", "TSLA",
	"GOOGL", "GOOG", "BRK.B", "JPM", "JNJ",
	"V", "UNH", "PG", "NVDA", "DIS", "MA", "HD",
	"PYPL", "BAC", "VZ", "CMCSA", "ADBE", "NFLX",
	"MRK", "INTC", "PFE", "T", "WMT", "TMO", "CRM",
	"XOM", "ABT", "PEP", "KO", "ABBV", "CSCO", "NKE",
	"AVGO", "QCOM", "CVX", "ACN", "COST", "MCD", "MDT",
	"TXN", "NEE", "DHR", "LLY", "BMY", "UNP", "HON", "LIN",
	"C", "AMGN", "WFC", "PM", "SBUX", "LOW", "ORCL", "AMD",
	"UPS", "IBM", "BA", "BLK", "MS", "RTX", "CAT",
	"NOW", "GS", "GE", "CVS", "INTU", "TGT", "ISRG",
	"AMT", "MMM", "CHTR", "DE", "BKNG", "SCHW", "AMAT",
	"MU", "FIS", "ANTM", "LMT", "TJX", "MDLZ", "ZTS",
	"CI", "SYK", "AXP", "GILD", "TMUS", "MO", "SPGI",
	"BDX", "LRCX", "CSX", "ADP", "CME", "CL", "ATVI", "PLD",
	"ADSK", "CB", "TFC", "USB", "PNC", "FISV", "ICE", "CCI",
	"DUK", "SO", "NSC", "APD", "DD", "VRTX", "EQIX", "GPN", "SHW",
	"ITW", "D", "FDX", "ADI", "EL", "HUM", "MMC", "GM", "EW", "PGR",
	"ECL", "ILMN", "DG", "REGN", "BSX", "ETN", "COF", "NEM", "EMR",
	"COP", "AON", "ROP", "NOC", "WM", "HCA",
	"KMB", "KLAC", "MCO", "FCX", "DOW", "IDXX", "TEL", "ROST", "CTSH", "BAX", "BIIB",
	"EA", "EXC", "APH", "ALGN", "CNC", "SNPS", "SYY", "CMG",
	"A", "APTV", "AEP", "LHX", "MCHP", "STZ", "TWTR", "MET", "CDNS",
	"MSCI", "BK", "XLNX", "JCI", "IQV", "DLR", "PH", "TT", "F",
	"DXCM", "HPQ", "EBAY", "PPG", "GD", "TROW", "ORLY", "CMI",
	"TRV", "EOG", "SLB", "AIG", "MNST", "WBA", "ALXN", "MAR",
	"SRE", "GIS", "CARR", "XEL", "PSA", "TDG", "ALL", "ZBH", "INFO",
	"CTVA", "YUM", "VRSK", "ANSS", "PRU", "RMD", "PSX", "HLT", "ES",
	"PCAR", "ROK", "CTAS", "MTD", "BLL", "MCK", "MSI", "AZO", "DFS",
	"PAYX", "AFL", "FAST", "ADM", "SBAC", "PEG", "KMI", "GLW", "AME",
	"FRC", "AWK", "MPC", "SWK", "LUV", "VFC", "KEYS", "STT", "WEC", "SPG",
	"OTIS", "SWKS", "DLTR", "WMB", "WLTW", "WELL", "BBY", "MXIM", "ENPH", "DAL",
	"CPRT", "LYB", "WY", "KR", "CLX", "CERN", "FTV", "VLO", "AMP", "TTWO",
	"ED", "EIX", "MKC", "VIAC", "DTE", "AJG", "ETSY", "DHI", "FLT", "TER", "SIVB",
	"EFX", "FITB", "WST", "VTRS", "HSY", "ZBRA", "AVB", "PXD", "VMC", "PPL",
	"KHC",
	"LH",
	"CHD",
	"PAYC",
	"CBRE",
	"LEN",
	"O",
	"QRVO",
	"MKTX",
	"IP",
	"NTRS",
	"HOLX",
	"RSG",
	"KSU",
	"ARE",
	"VRSN",
	"FTNT",
	"EQR",
	"SYF",
	"ODFL",
	"EXPE",
	"MLM",
	"CDW",
	"XYL",
	"TSN",
	"CTLT",
	"ETR",
	"ALB",
	"MTB",
	"TFX",
	"URI",
	"DOV",
	"AEE",
	"LVS",
	"OKE",
	"HAL",
	"AMCR",
	"GRMN",
	"KEY",
	"HIG",
	"BR",
	"PKI",
	"GWW",
	"COO",
	"TSCO",
	"INCY",
	"TYL",
	"VTR",
	"IR",
	"RF",
	"KMX",
	"NUE",
	"STE",
	"CFG",
	"AES",
	"OXY",
	"DGX",
	"AKAM",
	"HES",
	"WAT",
	"ANET",
	"FE",
	"ULTA",
	"CMS",
	"CAH",
	"DRI",
	"NDAQ",
	"CAG",
	"VAR",
	"CE",
	"CTXS",
	"EXPD",
	"IEX",
	"ABC",
	"WDC",
	"FMC",
	"POOL",
	"HPE",
	"DPZ",
	"PEAK",
	"BKR",
	"GPC",
	"K",
	"ESS",
	"HBAN",
	"CCL",
	"IT",
	"ABMD",
	"J",
	"MAS",
	"WAB",
	"NTAP",
	"EMN",
	"EXR",
	"DRE",
	"MAA",
	"BF.B",
	"NVR",
	"LDOS",
	"PKG",
	"TDY",
	"OMC",
	"AVY",
	"RCL",
	"CINF",
	"BIO",
	"PFG",
	"CHRW",
	"STX",
	"IFF",
	"SJM",
	"CXO",
	"XRAY",
	"BXP",
	"MGM",
	"JKHY",
	"RJF",
	"UAL",
	"HRL",
	"NLOK",
	"JBHT",
	"HAS",
	"WRK",
	"FBHS",
	"LNT",
	"EVRG",
	"FFIV",
	"AAP",
	"CNP",
	"PHM",
	"WHR",
	"LW",
	"TXT",
	"ALLE",
	"HWM",
	"LB",
	"ATO",
	"UDR",
	"L",
	"DVN",
	"CBOE",
	"LKQ",
	"UHS",
	"WYNN",
	"PWR",
	"LUMN",
	"HSIC",
	"LYV",
	"FOXA",
	"HST",
	"BWA",
	"NRG",
	"TPR",
	"IPG",
	"RE",
	"PNR",
	"LNC",
	"TAP",
	"WRB",
	"CPB",
	"SNA",
	"WU",
	"MOS",
	"CF",
	"FANG",
	"GL",
	"AAL",
	"DVA",
	"ROL",
	"DISCK",
	"MHK",
	"IPGP",
	"NWL",
	"CMA",
	"PNW",
	"NI",
	"ZION",
	"AIZ",
	"DISH",
	"IRM",
	"JNPR",
	"AOS",
	"NCLH",
	"NLSN",
	"PVH",
	"NWSA",
	"DXC",
	"SEE",
	"COG",
	"RHI",
	"IVZ",
	"BEN",
	"FLIR",
	"REG",
	"HII",
	"KIM",
	"APA",
	"ALK",
	"PRGO",
	"MRO",
	"PBCT",
	"NOV",
	"LEG",
	"FRT",
	"DISCA",
	"VNO",
	"HBI",
	"RL",
	"FTI",
	"FLS",
	"UNM",
	"VNT",
	"GPS",
	"FOX",
	"SLG",
	"XRX",
	"HFC",
	"UAA",
	"UA",
	"NWS",
}
